# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Tech life as Demigodgeek from zero to hero
email: gaodemi@outlook
description: >Experienced in business management consulting and project management for titans. Thrived and excelled in a demanding fintech bootcamp at UC Berkeley, where the enchanting world of coding, Machine Learning and Web 3.0 captured my imagination. 
I would love to bridge the gap between business and tech in this dynamic era of financial innovation.
 # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "main.demigodgeek.com" # the subpath of your site, e.g. /blog
url: "https://www.demigodgeek.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  Demigodgeek

# Build settings
markdown: kramdown
